# Generated by Django 6.0.7 on 2026-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Task description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is complited')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='todolist.tag', verbose_name='Tags')),
            ],
        ),
    ]
